/**
 * Cloudflare Worker — allworld
 * 多站点 R2 静态托管 + 26-riu-cfg-bid (D1/R2/ASSETS) 主机分流
 */

export interface Env {
  DB: D1Database
  STORAGE: R2Bucket
  SITES: R2Bucket
  ASSETS: Fetcher
  PROJECT_SLUG: string
  DEPLOYMENT_HOST: string
  ROOT_DOMAIN: string
}

type Role = 'GUEST' | 'AUDITOR' | 'AVIONICS_ADMIN'

interface SessionUser {
  id: string
  email: string
  display_name: string
  role: Role
}

const DEMO_CREDENTIALS: Record<string, string> = {
  'admin@softwarelink.net': 'Admin@2026!Sec',
  'auditor@softwarelink.net': 'Auditor@2026!Sec',
}

const CORS_HEADERS: HeadersInit = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Methods': 'GET,POST,PUT,PATCH,DELETE,OPTIONS',
  'Access-Control-Allow-Headers': 'Content-Type, Authorization',
}

function json(data: unknown, status = 200): Response {
  return new Response(JSON.stringify(data), {
    status,
    headers: {
      'Content-Type': 'application/json; charset=utf-8',
      ...CORS_HEADERS,
    },
  })
}

function crc32(bytes: Uint8Array): string {
  let crc = 0xffffffff
  for (let i = 0; i < bytes.length; i++) {
    crc ^= bytes[i]
    for (let j = 0; j < 8; j++) {
      crc = (crc >>> 1) ^ (crc & 1 ? 0xedb88320 : 0)
    }
  }
  return ((crc ^ 0xffffffff) >>> 0).toString(16).padStart(8, '0').toUpperCase()
}

async function sha256Hex(bytes: Uint8Array): Promise<string> {
  const digest = await crypto.subtle.digest('SHA-256', bytes)
  return [...new Uint8Array(digest)].map((b) => b.toString(16).padStart(2, '0')).join('')
}

function parseAuth(request: Request): SessionUser | null {
  const header = request.headers.get('Authorization')
  if (!header?.startsWith('Bearer ')) return null
  try {
    const payload = JSON.parse(utf8FromBase64(header.slice(7)))
    if (!payload?.id || !payload?.role) return null
    return payload as SessionUser
  } catch {
    return null
  }
}

function utf8ToBase64(str: string): string {
  const bytes = new TextEncoder().encode(str)
  let binary = ''
  bytes.forEach((b) => {
    binary += String.fromCharCode(b)
  })
  return btoa(binary)
}

function utf8FromBase64(b64: string): string {
  const binary = atob(b64)
  const bytes = new Uint8Array(binary.length)
  for (let i = 0; i < binary.length; i++) bytes[i] = binary.charCodeAt(i)
  return new TextDecoder().decode(bytes)
}

function encodeToken(user: SessionUser): string {
  return utf8ToBase64(JSON.stringify(user))
}

async function writeAudit(
  env: Env,
  userId: string | null,
  action: string,
  request: Request,
  payload: unknown = null,
) {
  const ip = request.headers.get('CF-Connecting-IP') || request.headers.get('X-Forwarded-For') || '127.0.0.1'
  await env.DB.prepare(
    'INSERT INTO audit_logs (user_id, action, ip_address, payload) VALUES (?, ?, ?, ?)',
  )
    .bind(userId, action, ip, payload ? JSON.stringify(payload) : null)
    .run()
}

function generateHeader(configName: string, busType: string, channels: ChannelInput[]): string {
  const guard = configName.toUpperCase().replace(/[^A-Z0-9]/g, '_') + '_H'
  const defs = channels
    .map(
      (ch, i) =>
        `  /* CH${i}: ${ch.label} */\n` +
        `  #define RIU_CH${i}_LABEL        "${ch.label}"\n` +
        `  #define RIU_CH${i}_BAUD         (${ch.baudRate}U)\n` +
        `  #define RIU_CH${i}_PARITY       (${ch.parity === 'ODD' ? 1 : ch.parity === 'EVEN' ? 2 : 0}U)\n` +
        `  #define RIU_CH${i}_FRAME_LEN    (${ch.frameLength}U)\n` +
        `  #define RIU_CH${i}_CYCLE_MS     (${ch.cycleMs}U)`,
    )
    .join('\n\n')

  return `/**
 * Autogenerated RIU ICD Header — DO NOT EDIT
 * Config : ${configName}
 * Bus    : ${busType}
 * Model  : Zero-malloc static memory, MISRA-C oriented
 */
#ifndef ${guard}
#define ${guard}

#include <stdint.h>

#define RIU_CHANNEL_COUNT (${channels.length}U)
#define RIU_BUS_TYPE_${busType} 1

${defs}

typedef struct {
  uint16_t channel_id;
  uint32_t baud_rate;
  uint8_t  parity;
  uint16_t frame_len;
  uint16_t cycle_ms;
} riu_channel_cfg_t;

extern const riu_channel_cfg_t g_riu_channels[RIU_CHANNEL_COUNT];
uint32_t riu_parse_frame(const uint8_t *buf, uint16_t len, uint16_t channel_id);

#endif /* ${guard} */
`
}

function generateSource(configName: string, busType: string, channels: ChannelInput[]): string {
  const table = channels
    .map(
      (ch, i) =>
        `  { ${i}U, ${ch.baudRate}U, ${ch.parity === 'ODD' ? 1 : ch.parity === 'EVEN' ? 2 : 0}U, ${ch.frameLength}U, ${ch.cycleMs}U }`,
    )
    .join(',\n')

  return `/**
 * Autogenerated RIU Parser Source — DO NOT EDIT
 * Config : ${configName}
 * Bus    : ${busType}
 * Constraint: no dynamic allocation (malloc-free)
 */
#include "riu_config.h"

const riu_channel_cfg_t g_riu_channels[RIU_CHANNEL_COUNT] = {
${table}
};

uint32_t riu_parse_frame(const uint8_t *buf, uint16_t len, uint16_t channel_id)
{
  uint32_t word = 0U;
  uint16_t i;

  if ((buf == 0) || (channel_id >= RIU_CHANNEL_COUNT)) {
    return 0U;
  }
  if (len < g_riu_channels[channel_id].frame_len) {
    return 0U;
  }

  for (i = 0U; i < g_riu_channels[channel_id].frame_len; i++) {
    word = (word << 8) | (uint32_t)buf[i];
  }
  return word;
}
`
}

interface ChannelInput {
  label: string
  baudRate: number
  parity: 'NONE' | 'ODD' | 'EVEN'
  frameLength: number
  cycleMs: number
}

function buildBinaryPayload(
  flashAddress: string,
  busType: string,
  channels: ChannelInput[],
): Uint8Array {
  const header = new Uint8Array(16)
  const addr = parseInt(flashAddress.replace(/^0x/i, ''), 16) || 0x08000000
  header[0] = 0x52 // R
  header[1] = 0x49 // I
  header[2] = 0x55 // U
  header[3] = 0x01 // version
  header[4] = (addr >>> 24) & 0xff
  header[5] = (addr >>> 16) & 0xff
  header[6] = (addr >>> 8) & 0xff
  header[7] = addr & 0xff
  header[8] = busType === 'ARINC429' ? 1 : busType === 'MIL_STD_1553B' ? 2 : busType === 'AFDX' ? 3 : 4
  header[9] = channels.length & 0xff
  header[10] = 0xaa
  header[11] = 0x55

  const body = new Uint8Array(channels.length * 12)
  channels.forEach((ch, idx) => {
    const o = idx * 12
    body[o] = idx & 0xff
    body[o + 1] = ch.parity === 'ODD' ? 1 : ch.parity === 'EVEN' ? 2 : 0
    body[o + 2] = (ch.baudRate >>> 8) & 0xff
    body[o + 3] = ch.baudRate & 0xff
    body[o + 4] = (ch.frameLength >>> 8) & 0xff
    body[o + 5] = ch.frameLength & 0xff
    body[o + 6] = (ch.cycleMs >>> 8) & 0xff
    body[o + 7] = ch.cycleMs & 0xff
    body[o + 8] = 0xde
    body[o + 9] = 0xad
    body[o + 10] = 0xbe
    body[o + 11] = 0xef
  })

  const out = new Uint8Array(header.length + body.length + 4)
  out.set(header, 0)
  out.set(body, header.length)
  const crc = crc32(out.subarray(0, out.length - 4))
  const crcVal = parseInt(crc, 16)
  out[out.length - 4] = (crcVal >>> 24) & 0xff
  out[out.length - 3] = (crcVal >>> 16) & 0xff
  out[out.length - 2] = (crcVal >>> 8) & 0xff
  out[out.length - 1] = crcVal & 0xff
  return out
}

function toHexDump(bytes: Uint8Array, baseAddr = 0x08000000): string {
  const lines: string[] = []
  for (let i = 0; i < bytes.length; i += 16) {
    const slice = bytes.subarray(i, Math.min(i + 16, bytes.length))
    const hex = [...slice].map((b) => b.toString(16).padStart(2, '0').toUpperCase()).join(' ')
    const ascii = [...slice].map((b) => (b >= 32 && b < 127 ? String.fromCharCode(b) : '.')).join('')
    lines.push(`${(baseAddr + i).toString(16).padStart(8, '0').toUpperCase()}  ${hex.padEnd(47, ' ')}  |${ascii}|`)
  }
  return lines.join('\n')
}

const ICD_TEMPLATES = [
  {
    id: 'tpl_arinc429_std',
    name: 'ARINC 429 Standard I/O Map',
    target_bus_type: 'ARINC429',
    flash_address_hex: '0x08010000',
    channels: [
      { label: 'ALT_BARO', baudRate: 100000, parity: 'ODD', frameLength: 4, cycleMs: 50 },
      { label: 'AIRSPEED', baudRate: 100000, parity: 'ODD', frameLength: 4, cycleMs: 50 },
      { label: 'HEADING', baudRate: 12500, parity: 'ODD', frameLength: 4, cycleMs: 100 },
      { label: 'LATITUDE', baudRate: 12500, parity: 'ODD', frameLength: 4, cycleMs: 200 },
    ],
  },
  {
    id: 'tpl_1553b_bc',
    name: 'MIL-STD-1553B BC Channel Set',
    target_bus_type: 'MIL_STD_1553B',
    flash_address_hex: '0x08020000',
    channels: [
      { label: 'BC_TX_CMD', baudRate: 1000000, parity: 'ODD', frameLength: 20, cycleMs: 20 },
      { label: 'RT_STATUS', baudRate: 1000000, parity: 'ODD', frameLength: 20, cycleMs: 20 },
      { label: 'BM_MONITOR', baudRate: 1000000, parity: 'NONE', frameLength: 32, cycleMs: 40 },
    ],
  },
  {
    id: 'tpl_hybrid_discrete',
    name: 'Hybrid Analog/Discrete Map',
    target_bus_type: 'HYBRID',
    flash_address_hex: '0x08030000',
    channels: [
      { label: 'DISC_WOW', baudRate: 0, parity: 'NONE', frameLength: 1, cycleMs: 10 },
      { label: 'ANALOG_FUEL', baudRate: 0, parity: 'NONE', frameLength: 2, cycleMs: 100 },
      { label: 'AFDX_VL_42', baudRate: 100000000, parity: 'NONE', frameLength: 64, cycleMs: 10 },
    ],
  },
]

async function handleApi(request: Request, env: Env, url: URL): Promise<Response> {
  const path = url.pathname.replace(/\/+$/, '') || '/'
  const method = request.method.toUpperCase()
  const user = parseAuth(request)

  if (method === 'OPTIONS') {
    return new Response(null, { status: 204, headers: CORS_HEADERS })
  }

  // Auth
  if (path === '/api/auth/login' && method === 'POST') {
    const body = (await request.json()) as { email?: string; password?: string }
    const email = (body.email || '').trim().toLowerCase()
    const password = body.password || ''
    if (!DEMO_CREDENTIALS[email] || DEMO_CREDENTIALS[email] !== password) {
      return json({ ok: false, error: '邮箱或密码错误' }, 401)
    }
    const row = await env.DB.prepare('SELECT id, email, display_name, role FROM users WHERE email = ?')
      .bind(email)
      .first<SessionUser>()
    if (!row) return json({ ok: false, error: '用户不存在' }, 404)
    const token = encodeToken(row)
    await writeAudit(env, row.id, 'AUTH_LOGIN', request, { email })
    return json({ ok: true, token, user: row })
  }

  if (path === '/api/auth/me' && method === 'GET') {
    if (!user) return json({ ok: false, error: '未登录' }, 401)
    return json({ ok: true, user })
  }

  if (path === '/api/auth/logout' && method === 'POST') {
    await writeAudit(env, user?.id || null, 'AUTH_LOGOUT', request)
    return json({ ok: true })
  }

  // Tender
  if (path === '/api/tender' && method === 'GET') {
    const tender = await env.DB.prepare('SELECT * FROM tender_items ORDER BY publish_time DESC LIMIT 1').first()
    if (!tender) return json({ ok: false, error: '未找到招标公告' }, 404)

    const deadline = new Date(String(tender.deadline).replace(' ', 'T') + '+08:00').getTime()
    const now = Date.now()
    const remainMs = Math.max(0, deadline - now)

    const qualifications = [
      { id: 'q1', label: '2025年度审计报告', required: true, status: 'PENDING', note: '需加盖公章扫描件' },
      { id: 'q2', label: 'CA数字证书办理流程', required: true, status: 'PENDING', note: '龙集采平台认证' },
      { id: 'q3', label: '非失信被执行人证明', required: true, status: 'PENDING', note: '法院公开查询截图' },
      { id: 'q4', label: '航空软件研发业绩', required: true, status: 'OPTIONAL', note: '同类RIU/ICD项目优先' },
      { id: 'q5', label: '保密资质/人员备案', required: false, status: 'OPTIONAL', note: '按招标文件要求提交' },
    ]

    return json({
      ok: true,
      tender,
      countdown: {
        deadline: tender.deadline,
        remainMs,
        remainDays: Math.floor(remainMs / 86400000),
        remainHours: Math.floor((remainMs % 86400000) / 3600000),
        remainMinutes: Math.floor((remainMs % 3600000) / 60000),
        remainSeconds: Math.floor((remainMs % 60000) / 1000),
        isExpired: remainMs <= 0,
      },
      qualifications,
      contacts: [
        { role: '招标代理', name: '中航招采科技（北京）有限公司', phone: '010-XXXX-8801', email: 'riu-bid@avic-demo.example' },
        { role: '技术咨询', name: '西安航空计算技术研究所项目组', phone: '029-XXXX-6610', email: 'riu-tech@xac-demo.example' },
      ],
      milestones: [
        { day: 30, title: '详细设计完成', desc: 'ICD元模型与生成器架构锁定' },
        { day: 45, title: '软硬件完成', desc: 'PC工具与Flash镜像链路闭环' },
        { day: 60, title: '调试与最终交付', desc: '联合编译验证与验收交付' },
      ],
    })
  }

  // RIU templates
  if (path === '/api/riu/templates' && method === 'GET') {
    return json({ ok: true, templates: ICD_TEMPLATES })
  }

  // RIU generate
  if (path === '/api/riu/generate' && method === 'POST') {
    if (user && user.role === 'GUEST') {
      return json({ ok: false, error: '访客仅可预览，不可生成' }, 403)
    }
    // Allow unauthenticated read-only validation? PRD says GUEST Read-Only Preview.
    // Generation for AUDITOR = validation, AVIONICS_ADMIN = full. Allow guest? No.
    // But for demo UX, allow generate for auditor+admin; guest gets 403.
    // If no user, treat as GUEST.
    if (!user) {
      return json({ ok: false, error: '请登录后执行生成。访客仅可预览模板。' }, 401)
    }

    const body = (await request.json()) as {
      config_name?: string
      version?: string
      target_bus_type?: string
      flash_address_hex?: string
      channels?: ChannelInput[]
      persist?: boolean
    }

    const configName = body.config_name || 'riu_config'
    const version = body.version || '1.0.0'
    const busType = (body.target_bus_type || 'ARINC429') as string
    const flashAddress = body.flash_address_hex || '0x08010000'
    const channels = (body.channels && body.channels.length ? body.channels : ICD_TEMPLATES[0].channels) as ChannelInput[]

    const hCode = generateHeader(configName, busType, channels)
    const cCode = generateSource(configName, busType, channels)
    const binary = buildBinaryPayload(flashAddress, busType, channels)
    const crc = crc32(binary)
    const sha = await sha256Hex(binary)
    const hexDump = toHexDump(binary, parseInt(flashAddress.replace(/^0x/i, ''), 16) || 0x08010000)

    let savedId: string | null = null
    if (body.persist && user.role === 'AVIONICS_ADMIN') {
      savedId = `riu_${Date.now().toString(36)}`
      await env.DB.prepare(
        `INSERT INTO riu_configurations
         (id, config_name, version, target_bus_type, flash_address_hex, binary_size_bytes, crc32_checksum, generated_c_code, generated_h_code, created_by)
         VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
      )
        .bind(savedId, configName, version, busType, flashAddress, binary.length, crc, cCode, hCode, user.id)
        .run()

      try {
        await env.STORAGE.put(`riu/${savedId}.bin`, binary, {
          httpMetadata: { contentType: 'application/octet-stream' },
          customMetadata: { crc32: crc, sha256: sha },
        })
      } catch {
        // R2 may be unavailable in some local setups; ignore storage failure for demo
      }
    }

    await writeAudit(env, user.id, 'RIU_GENERATE', request, {
      configName,
      busType,
      size: binary.length,
      crc,
      persist: Boolean(body.persist),
    })

    return json({
      ok: true,
      result: {
        id: savedId,
        config_name: configName,
        version,
        target_bus_type: busType,
        flash_address_hex: flashAddress,
        binary_size_bytes: binary.length,
        crc32_checksum: crc,
        sha256_checksum: sha,
        generated_h_code: hCode,
        generated_c_code: cCode,
        hex_dump: hexDump,
        binary_base64: btoa(String.fromCharCode(...binary)),
        misra_notes: [
          '无动态内存分配 (malloc-free)',
          '固定长度通道表 g_riu_channels[]',
          '空指针与边界检查完整',
          'uintN_t 定宽整数',
        ],
      },
    })
  }

  // Verify artifact
  if (path === '/api/riu/verify' && method === 'POST') {
    const body = (await request.json()) as { binary_base64?: string; expected_crc32?: string }
    if (!body.binary_base64) return json({ ok: false, error: '缺少 binary_base64' }, 400)
    const raw = Uint8Array.from(atob(body.binary_base64), (c) => c.charCodeAt(0))
    const crc = crc32(raw)
    const sha = await sha256Hex(raw)
    const match = body.expected_crc32 ? body.expected_crc32.toUpperCase() === crc : true
    await writeAudit(env, user?.id || null, 'RIU_VERIFY', request, { crc, match })
    return json({ ok: true, crc32: crc, sha256: sha, match, size: raw.length })
  }

  // System configs
  if (path === '/api/system/configs' && method === 'GET') {
    if (!user || (user.role !== 'AUDITOR' && user.role !== 'AVIONICS_ADMIN')) {
      return json({ ok: false, error: '权限不足' }, 403)
    }
    const { results } = await env.DB.prepare('SELECT * FROM system_configs ORDER BY is_feature_flag DESC, config_key').all()
    return json({ ok: true, configs: results })
  }

  if (path === '/api/system/configs' && method === 'PUT') {
    if (!user || user.role !== 'AVIONICS_ADMIN') {
      return json({ ok: false, error: '仅 AVIONICS_ADMIN 可修改' }, 403)
    }
    const body = (await request.json()) as { config_key: string; config_value: string }
    await env.DB.prepare(
      'UPDATE system_configs SET config_value = ?, updated_at = CURRENT_TIMESTAMP WHERE config_key = ?',
    )
      .bind(body.config_value, body.config_key)
      .run()
    await writeAudit(env, user.id, 'CONFIG_UPDATE', request, body)
    return json({ ok: true })
  }

  // Audit logs
  if (path === '/api/audit/logs' && method === 'GET') {
    if (!user || (user.role !== 'AUDITOR' && user.role !== 'AVIONICS_ADMIN')) {
      return json({ ok: false, error: '权限不足' }, 403)
    }
    const { results } = await env.DB.prepare(
      'SELECT * FROM audit_logs ORDER BY timestamp DESC LIMIT 100',
    ).all()
    return json({ ok: true, logs: results })
  }

  // Health
  if (path === '/api/health' && method === 'GET') {
    let dbOk = false
    try {
      await env.DB.prepare('SELECT 1').first()
      dbOk = true
    } catch {
      dbOk = false
    }
    return json({
      ok: true,
      service: '26-riu-cfg-bid',
      db: dbOk ? 'up' : 'down',
      host: env.DEPLOYMENT_HOST,
      ts: new Date().toISOString(),
    })
  }

  // Saved RIU configs list
  if (path === '/api/riu/configs' && method === 'GET') {
    if (!user || (user.role !== 'AUDITOR' && user.role !== 'AVIONICS_ADMIN')) {
      return json({ ok: false, error: '权限不足' }, 403)
    }
    const { results } = await env.DB.prepare(
      'SELECT id, config_name, version, target_bus_type, flash_address_hex, binary_size_bytes, crc32_checksum, created_by, created_at FROM riu_configurations ORDER BY created_at DESC LIMIT 50',
    ).all()
    return json({ ok: true, configs: results })
  }

  return json({ ok: false, error: `Unknown API route: ${method} ${path}` }, 404)
}

function siteIdFromHost(hostname: string, rootDomain: string): string {
  const host = hostname.toLowerCase()
  const root = rootDomain.toLowerCase()
  if (host === root) return '_root'
  if (host === `www.${root}`) return 'www'
  if (host.endsWith(`.${root}`)) return host.slice(0, -(root.length + 1))
  return host
}

function isRiuHost(hostname: string, env: Env): boolean {
  const host = hostname.toLowerCase()
  const root = (env.ROOT_DOMAIN || 'softwarelink.net').toLowerCase()
  const slug = (env.PROJECT_SLUG || '26-riu-cfg-bid').toLowerCase()
  return host === `${slug}.${root}` || host.startsWith(`${slug}.`)
}

function contentTypeFor(path: string): string {
  const ext = path.split('.').pop()?.toLowerCase() || ''
  const map: Record<string, string> = {
    html: 'text/html; charset=utf-8',
    js: 'application/javascript; charset=utf-8',
    css: 'text/css; charset=utf-8',
    json: 'application/json; charset=utf-8',
    svg: 'image/svg+xml',
    png: 'image/png',
    jpg: 'image/jpeg',
    jpeg: 'image/jpeg',
    webp: 'image/webp',
    ico: 'image/x-icon',
    txt: 'text/plain; charset=utf-8',
    map: 'application/json',
    xml: 'application/xml; charset=utf-8',
    woff: 'font/woff',
    woff2: 'font/woff2',
  }
  return map[ext] || 'application/octet-stream'
}

function emptySitePage(siteId: string): Response {
  if (siteId === '_root' || siteId === 'www') {
    const html = `<!DOCTYPE html>
<html lang="zh-CN">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>allworld · softwarelink.net</title>
  <style>
    :root { --ink:#0f172a; --muted:#64748b; --bg:#f8fafc; }
    body { margin:0; font-family:"Segoe UI",system-ui,sans-serif; color:var(--ink);
      background: radial-gradient(1000px 500px at 0% 0%,#e0f2fe,transparent 55%),
                  radial-gradient(800px 400px at 100% 0%,#fef3c7,transparent 50%), var(--bg);
      min-height:100vh; }
    main { max-width:42rem; margin:0 auto; padding:4rem 1.25rem; }
    h1 { font-size:clamp(2rem,5vw,3rem); letter-spacing:-0.04em; margin:0 0 .75rem; }
    p,li { color:var(--muted); line-height:1.7; }
    code { background:#e2e8f0; padding:.15em .4em; border-radius:4px; font-size:.92em; }
    a { color:#0284c7; }
  </style>
</head>
<body>
  <main>
    <h1>allworld</h1>
    <p>softwarelink.net 多站点边缘托管入口（Worker <code>allworld</code> + R2 <code>allworld-sites</code>）。</p>
    <ul>
      <li>子域站点：<code>{site}.softwarelink.net</code> → R2 前缀 <code>{site}/</code></li>
      <li>RIU 招标门户：<a href="https://26-riu-cfg-bid.softwarelink.net/">26-riu-cfg-bid.softwarelink.net</a></li>
    </ul>
  </main>
</body>
</html>`
    return new Response(html, { headers: { 'Content-Type': 'text/html; charset=utf-8' } })
  }

  const html = `<!DOCTYPE html>
<html lang="zh-CN">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>${siteId}</title>
  <style>
    body { margin:0; font-family:system-ui,sans-serif; background:#f8fafc; color:#0f172a;
      min-height:100vh; display:grid; place-items:center; }
    main { max-width:36rem; padding:2rem; }
    h1 { margin:0 0 .5rem; letter-spacing:-0.03em; }
    p { color:#64748b; line-height:1.6; }
    code { background:#e2e8f0; padding:.1em .35em; border-radius:4px; }
  </style>
</head>
<body>
  <main>
    <h1>${siteId}</h1>
    <p>R2 尚无静态文件。上传 <code>dist/</code> 或 <code>PUT /index.html</code>。</p>
    <p>演示数据：<code>PUT /api/data/demo</code></p>
  </main>
</body>
</html>`
  return new Response(html, { headers: { 'Content-Type': 'text/html; charset=utf-8' } })
}

async function serveR2Site(request: Request, env: Env): Promise<Response> {
  const url = new URL(request.url)
  const siteId = siteIdFromHost(url.hostname, env.ROOT_DOMAIN || 'softwarelink.net')

  // Minimal platform API stubs used by other sites' tooling
  if (url.pathname === '/api/data/demo' && request.method === 'PUT') {
    return json({ ok: true, site: siteId, message: 'demo accepted' })
  }
  if (url.pathname.startsWith('/api/')) {
    return json({ ok: false, error: 'Not Found' }, 404)
  }

  let pathname = decodeURIComponent(url.pathname)
  if (pathname.endsWith('/')) pathname += 'index.html'
  if (pathname === '') pathname = '/index.html'

  const candidates = [
    `${siteId}${pathname}`,
    `${siteId}${pathname}.html`,
    `${siteId}${pathname}/index.html`,
    `${siteId}/index.html`,
  ]

  for (const key of candidates) {
    const obj = await env.SITES.get(key)
    if (!obj) continue
    const headers = new Headers()
    headers.set('Content-Type', obj.httpMetadata?.contentType || contentTypeFor(key))
    if (obj.httpEtag) headers.set('ETag', obj.httpEtag)
    return new Response(obj.body, { headers })
  }

  // SPA fallback: if site has index.html, serve it for extensionless paths
  if (!pathname.split('/').pop()?.includes('.')) {
    const indexObj = await env.SITES.get(`${siteId}/index.html`)
    if (indexObj) {
      return new Response(indexObj.body, {
        headers: { 'Content-Type': 'text/html; charset=utf-8' },
      })
    }
  }

  return emptySitePage(siteId)
}

export default {
  async fetch(request: Request, env: Env): Promise<Response> {
    const url = new URL(request.url)

    // RIU portal (API + Workers Assets SPA)
    if (isRiuHost(url.hostname, env)) {
      if (url.pathname.startsWith('/api/')) {
        try {
          return await handleApi(request, env, url)
        } catch (err) {
          const message = err instanceof Error ? err.message : 'Internal error'
          return json({ ok: false, error: message }, 500)
        }
      }
      if (env.ASSETS) {
        return env.ASSETS.fetch(request)
      }
      return new Response('ASSETS binding not configured', { status: 500 })
    }

    // Other softwarelink.net sites → allworld-sites R2
    try {
      return await serveR2Site(request, env)
    } catch (err) {
      const message = err instanceof Error ? err.message : 'Internal error'
      return json({ ok: false, error: message }, 500)
    }
  },
}
